site_name: Open Radar Data documentation
site_description: Guidance and instructions for Open Radar Data users
site_author: EUMETNET
repo_url: https://github.com/EUMETNET/openradardata-documentation
theme:
  name: material
  language: en
  logo: images/meteogate-logo.svg
  palette:
    primary: black
    accent: indigo
  font:
    text: Open Sans
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.highlight
    - content.code.copy

nav:
  - HOME: 1-ORD-API-overview.md
  - 2. DISCOVERING AND ACCESSING DATA: 2-ORD-API-discovering-and-accessing-data.md
  - 3. PUBLISHING DATA: 3-ORD-API-publishing-data.md
  - 4. SUBSCRIBING MQTTX: 4-ORD-API-subscribing-MQTTX.md
